### PR TITLE
Make loading of previously trained model work

### LINKED ISSUE #52: loading of previously trained models
Hi, 
I have an issue concerning the master-branch, where loading of trained models into clstmocrtrain is implemented but not working (for me). I have audited the code but cannot find what issues the following error with a given load- and/or start-parameter.
got 950 files, 50 tests
.Stacked: 0.0001 0.9 in 0 48 out 0 74
FATAL: missing parameter

Best wishes

### PR DESCRIPTION
**Pull request by amitdo**
Fixes #52

### CODE REVIEW

**Comment by amitdo** [comment]
@tmbdev, 
Please fix the broken CircleCI setup.

This PR compiles fine on my machine, which is Ubuntu 14.04 64bit with Eigen 3.3 alpha.

**Comment by stexandev** [comment]
Thank you for your quick response and solid fix. Recompiled and tested the fix with three different models and worked flawless. Testing included loading previously trained models, training until next save, loading again. Everything seems fine.

**Comment by amitdo** [comment]
@stexandev 
Glad to help!

**Comment by isaomatsunami** [comment]
Current code still fails with "FATAL missing parameter"
this parameter seems to be lrate.

Is this parameter stored in saved .clstm data?

**Comment by amitdo** [comment]
Tom didn't merge this PR with the master yet. That's why the "current code still fails"...

**Comment by amitdo** [comment]
Tom, FYI @isaomatsunami confirned elsewhere:

> patched code works perfectly.

**Pull request merged**
