### PR TITLE
README: "Prerequisites" section, with info for Ubuntu 14.04

### PR DESCRIPTION
**Pull request by kba**
Since I needed that for CircleCI and there were questions on installation in 14.04 in gitter.

### CODE REVIEW

**Comment by amitdo** [comment]
First you say 'Download' from Eigen site

> Download [Eigen](http://eigen.tuxfamily.org) with Tensor support (> v3.3-beta1)
> and copy the header files to an `include` path:

but then you give an example that uses git and clone Eigen's repo.

``` sh
sudo git clone --depth 1 --single-branch --branch 3.3-rc1 \
  "https://github.com/RLovelett/eigen" /usr/local/include/eigen3
```

Why to use git just to download a (pre)release?

**Comment by amitdo** [comment]
There are two options to download the rc1:
https://github.com/RLovelett/eigen/archive/3.3-rc1.tar.gz
http://bitbucket.org/eigen/eigen/get/3.3-rc1.tar.gz

**Comment by amitdo** [comment]
Also, hdf5 is not really needed, so why mention it?

**Comment by kba** [comment]
> First you say 'Download' from Eigen site
> Why to use git just to download a (pre)release?

Because the tarballs contain the same data but with a directory with the commit-SHA1 (c.f. a645a3e72ff522b3e16589200d653c4406ffe1e2: `curl 'http://bitbucket.org/eigen/eigen/get/3.3-rc1.tar.gz' | tar xf;
sudo mv 'eigen-eigen-bef509908b9d' /usr/local/include/eigen3`) With git it's a single command and once the upstream Eigen is updated, we only need to change `3.3-rc1` to `3.3-rc2` or `3.3` or whatever. Plus, if people install clstm, they have git. But do they have curl? Or wget?

> Also, hdf5 is not really needed, so why mention it?

Before, the README listed them in the one `apt-get install` command. My intent was to highlight that they are not really needed. If we remove the hdf5 libs from prerequisites, we should also remove the `scons` option. Same for the display debugging stuff.

**Comment by amitdo** [comment]
I just think git is overkill for the purpose of downloading a software. 

Not every potential user is a developer (who already installed git).
I believe wget is installed by default in Debian/Ubuntu. Same for untar/unzip.

With https://github.com/RLovelett/eigen/archive/3.3-rc1.tar.gz
the directory is `eigen-3.3-rc1`

Just my opinion :)

**Comment by amitdo** [comment]
BTW, Git depends on libcurl (libcurl3-gnutls in Debian/Ubuntu).

**Comment by zuphilip** [comment]
I think it is save to assume that every potential user of CLSTM has any of the tools installed or does know how to install them. Moreover, as I understand @kba, to copy the files of CLSTM itself one will use `git` anyway. That is fine for me. (BTW previously the command `hg` for the mercurial repo was used.)

**Comment by kba** [comment]
Compromise?

``` sh
# with wget
wget 'https://github.com/RLovelett/eigen/archive/3.3-rc1.tar.gz'
tar xf 3.3-rc1.tar.gz
mv eigen-3.3-rc1 /usr/local/include
# or with git:
sudo git clone --depth 1 --single-branch --branch 3.3-rc1 \
  "https://github.com/RLovelett/eigen" /usr/local/include/eigen3
```

BTW: unzip is not installed by default in many distros. Some distros tend to have wget, some curl. curl doesn't follow 3xx per default, wget saves to a file per default including URL query. I Stumble upon these differences a lot with Docker, CI and different distros at work/at home... Granted though with the ancient git pre-installed in some distros you have the same problems.

**Comment by amitdo** [comment]
Fair enough :)

**Comment by amitdo** [comment]
What about scons, how a user should get it?

https://github.com/tmbdev/clstm/pull/21/commits/449ffcc8
~~scons~~ ... -> apt-get ...

It should be:
apt-get scons ...

**Comment by kba** [comment]
> What about scons, how a user should get it?

https://github.com/kba/clstm/commit/a645a3e72ff522b3e16589200d653c4406ffe1e2

```
# Ubuntu 15.04 / Debian 8
sudo apt-get install scons libprotobuf-dev libprotobuf9 protobuf-compiler

# Ubuntu 14.04:
sudo apt-get install scons libprotobuf-dev libprotobuf8 protobuf-compiler
```

**Comment by amitdo** [comment]
Forgive  me. I missed that part.

**Pull request merged**
