### PR TITLE
README: CircleCI status badge

### PR DESCRIPTION
**Pull request by kba**

### CODE REVIEW

**Comment by zuphilip** [comment]
Did the test run through now?

**Comment by kba** [comment]
https://github.com/tmbdev/clstm/blob/905f90f7671b98642402b9e4b2a6b09a82fa542a/README.md :-)

**Comment by zuphilip** [comment]
The CircleCI fails currently https://circleci.com/gh/tmbdev/clstm/tree/master, also the test for this PR was fine. I guess it is unrelated to the change of the README here. Anyway would be good to fix this.

**Comment by stweil** [comment]
See PR #102.

**Pull request merged**
